### ISSUE TITLE
Laptop Kabel mitgenommen

### ISSUE THREAD

**Issue by k1llerk3ks** [Windfisch/eh21-b3d-workshop#1]
Ich schreibe im Auftrag von meinem Kumpel, du hast wohl das Ladekabel seines Laptops mitgenommen. Er wird morgen wohl meist zwischen Chaos Post und Wallhacka sitzen. Sonst, ich kann auch (sowas wie Telegram) vermitteln. Er kommt leider nicht in seinen GitHub Account rein... thx!

*Edit: Ist leider wirklich dringend, er ist morgen früh ab 08:00 dort. Du kannst es auch gern bei der Chaospost abgeben, so viel Vertrauen ist glaub ich da :)

**Comment by Windfisch** [comment]
aloha! ich habe schon auf mastodon getootet deswegen, ja :D Danke fürs ausleihen, er war leider schon weg :D

Ich versuch, ihn morgen da zu finden. Ansonsten DECT: 9463 oder im Himmel nach Windfisch fragen

31.03.2024 00:48:10 Irony? ***@***.***>:
